data_local: ./my-copy-c4
data_remote:  # If blank, files must be present in data_local
tokenizer_name: facebook/opt-2.7b
max_seq_len: 4096
global_seed: 17

# Run Name
run_name:  # If left blank, will be read from env var $RUN_NAME
timing_file: /nfs/scistore19/alistgrp/stang/llm-foundry/timing_file/LLama3-8b-A6000.txt

max_split_size_mb: 512
# Model
model:
  name: hf_causal_lm
  # pretrained_model_name_or_path: meta-llama/Meta-Llama-3-8B
  pretrained_model_name_or_path: Shengkun/Llama3-8B-Structural-Pruning-1.5

  pretrained: true
  # init_device: meta
  use_auth_token: true
  use_flash_attention_2: true

# Tokenizer
tokenizer:
  # name: meta-llama/Meta-Llama-3-8B
  name: Shengkun/Llama3-8B-Structural-Pruning-1.5
  kwargs:
    model_max_length: ${max_seq_len}

# Dataloaders
train_loader:
  name: finetuning
  dataset:
    # local: ${data_local}
    hf_name: Open-Orca/OpenOrca
    decoder_only_format: true
    remote: ${data_remote}
    split: train
    shuffle: true
    max_seq_len: ${max_seq_len}
    shuffle_seed: ${global_seed}
  drop_last: true
  num_workers: 8

# eval_loader:
#   name: finetuning
#   dataset:
#     # local: ${data_local}
#     hf_name: mosaicml/dolly_hhrlhf
#     decoder_only_format: true
#     remote: ${data_remote}
#     split: test
#     shuffle: false
#     max_seq_len: ${max_seq_len}
#     shuffle_seed: ${global_seed}
#   drop_last: false
#   num_workers: 8

# Optimization
scheduler:
  name: cosine_with_warmup
  t_warmup: 100ba
  alpha_f: 0.1

optimizer:
  name: decoupled_adamw
  lr: 6.0e-4
  betas:
  - 0.9
  - 0.95
  eps: 1.0e-08
  weight_decay: 0.0

algorithms:
  gradient_clipping:
    clipping_type: norm
    clipping_threshold: 1.0

max_duration: 4800ba  # ~ 2.5B tokens
eval_interval: 500ba
eval_first: false
eval_subset_num_batches: -1
global_train_batch_size: 1

# System
seed: ${global_seed}
device_eval_batch_size: 16
device_train_microbatch_size: 64
# device_train_microbatch_size: auto
precision: amp_bf16

# FSDP
fsdp_config:
  sharding_strategy: FULL_SHARD
  mixed_precision: PURE
  activation_checkpointing: true
  activation_checkpointing_reentrant: false
  activation_cpu_offload: false
  limit_all_gathers: true

# Logging
progress_bar: false
log_to_console: true
console_log_interval: 1ba

callbacks:
  speed_monitor:
    window_size: 10
  lr_monitor: {}
  memory_monitor: {}
  runtime_estimator: {}

# loggers:
#   wandb: {}

# Checkpoint to local filesystem or remote object store
# save_interval: 500ba
# save_num_checkpoints_to_keep: 1  # Important, this cleans up checkpoints saved to DISK
# save_folder: ./{run_name}/checkpoints
# save_folder: s3://my-bucket/my-folder/{run_name}/checkpoints

# Load from local filesystem or remote object store
# load_path: ./gpt-125m/checkpoints/latest-rank{rank}.pt
# load_path: s3://my-bucket/my-folder/gpt-125m/checkpoints/latest-rank{rank}.pt
